"""Add expiry_date to Product model

Revision ID: 2e7f7596a944
Revises: 67643e56aa58
Create Date: 2025-05-16 20:13:16.052035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7f7596a944'
down_revision = '67643e56aa58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_expiry_date'), ['expiry_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_expiry_date'))
        batch_op.drop_column('expiry_date')

    # ### end Alembic commands ###
