"""Add sale return models

Revision ID: 7c9c6e532f7e
Revises: e9fbd9355484
Create Date: 2025-04-29 23:38:46.578456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9c6e532f7e'
down_revision = 'e9fbd9355484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_timestamp', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('total_refunded_amount', sa.Float(), nullable=False),
    sa.Column('original_sale_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('processed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['original_sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['processed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_returns_return_timestamp'), ['return_timestamp'], unique=False)

    op.create_table('sale_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_return_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('amount_refunded', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_return_id'], ['sale_returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_return_items')
    with op.batch_alter_table('sale_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_returns_return_timestamp'))

    op.drop_table('sale_returns')
    # ### end Alembic commands ###
